### ISSUE TITLE
Undefined variable 'prob_correct_answer' in boundpairs.m

### ISSUE THREAD

**Issue by jyhong0304** [TUC-ProAut/VSA_Toolbox#1]
First of all, I want to say that your paper is great, and really appreciate for sharing your code so others including me can try it.
Thanks to your paper, I have definitely been able to get a better understanding of VSAs.
I would like to inform you that an error occurred when trying to run your code. 

At line 93 in `boundpairs.m` in the `experimental_scripts` folder,

`prob_correct_array(d_idx,:) = prob_correct_answer;`

should be changed as follows:

`prob_correct_array(d_idx,:) = prob_correct;`

because the `prob_correct_answer` is an undefined variable.
I confirmed that it worked properly after correcting it.

**Comment by scken** [comment]
Thanks for the comment and the kind words. 
I have updated the code and fixed the error.

If there are more questions, don't hesitate to contact us. 

Best regards
